# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: resortfinder
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reaping_frequency: 30

development:
  <<: *default
  database: resortfinder_development
  password: <%= Rails.application.secrets[:database][:password] %>

test:
  <<: *default
  database: resortfinder_test
  password: <%= Rails.application.secrets[:database][:password] %>

production:
  <<: *default
  database: resortfinder_production
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>
