# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  database:
    :password: 'resortfinder'
  secret_key_base: 477b8dd457288347f66fb95a8356289b983deb935eae3f0774bc35735b0f408c6ea1ce6c89b7375f2503b5eda0a346b39a0c12ba83c0cd6f313c5c0675b85ae2

test:
  database:
    :password: 'resortfinder'
  secret_key_base: e12cafea0bc05f5f8080fc8150ab4467da1a99c3e8465242f02212b1f695704134f64f99b73d400e1d353abc61b14ca45d5fd8d0bfb279985211496564535fba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  database:
    :password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
